# http://www.ncbi.nlm.nih.gov/pubmed/?term=beatrycze+nowicka
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
import string
import gensim
from gensim import corpora

abs1 = "In the present studies, we focused on substrate specificity of tocopherol cyclase, the key enzyme in the biosynthesis of the tocopherols and plastochromanol-8, the main plant lipid antioxidants, with special emphasis on the preference for tocopherols and plastochromanol-8 precursors, taking advantage of the recombinant enzyme originating from Arabidopsis thaliana and isolated plastoglobules, thylakoids and various model systems like micelles and thylakoids. Plastoglobules and triacylglycerol micelles were the most efficient reaction environment for the cyclase. In various investigated systems, synthesis of γ-tocopherol proceeded considerably faster than that of plastochromanol-8, probably mainly due to different localization of the corresponding substrates in the analyzed lipid structures. Moreover, our study was complemented by bioinformatics analysis of the phylogenetic relations of the cyclases and sequence motifs, crucial for the enzyme activity, were proposed. The analysis revealed also a group of tocopherol cyclase-like proteins in a number of heterotrophic bacterial species, with a conserved region common with photosynthetic organisms, that might be engaged in the catalytic activity of both groups of organisms."

abs2 = "This review examines various aspects of vitamin E, both in plant metabolism and with regard to its importance for human health. Vitamin E is the collective name of a group of lipid-soluble compounds, chromanols, which are widely distributed in the plant kingdom. Their biosynthetic pathway, intracellular distribution and antioxidant function in plants is well recognized, although their other functions are also considered. Analytical methods for the determination of vitamin E are discussed in detail. Furthermore, the vitamin E metabolism and its antioxidant action in humans is described. Other non-antioxidant functions of vitamin E are also presented, such as its anti-inflammatory effects, role in the prevention of cardiovascular diseases and cancer, as well as its protective functions against neurodegenerative and other diseases."

abs3 = "Photosynthesis is a complex metabolic process enabling photosynthetic organisms to use solar energy for the reduction of carbon dioxide into biomass. This ancient pathway has revolutionized life on Earth. The most important event was the development of oxygenic photosynthesis. It had a tremendous impact on the Earth's geochemistry and the evolution of living beings, as the rise of atmospheric molecular oxygen enabled the development of a highly efficient aerobic metabolism, which later led to the evolution of complex multicellular organisms. The mechanism of photosynthesis has been the subject of intensive research and a great body of data has been accumulated. However, the evolution of this process is not fully understood, and the development of photosynthesis in prokaryota in particular remains an unresolved question. This review is devoted to the occurrence and main features of phototrophy and photosynthesis in prokaryotes. Hypotheses concerning the origin and spread of photosynthetic traits in bacteria are also discussed."

abs4 = "Acclimation to heavy metal-induced stress is a complex phenomenon. Among the mechanisms of heavy metal toxicity, an important one is the ability to induce oxidative stress, so that the antioxidant response is crucial for providing tolerance to heavy metal ions. The effect of chronic stress induced by ions of five heavy metals, Ag, Cu, Cr (redox-active metals) Cd, Hg (nonredox-active metals) on the green microalga Chlamydomonas reinhardtii was examined at two levels - the biochemical (content of photosynthetic pigments and prenyllipid antioxidants, lipid peroxidation) and the physiological (growth rate, photosynthesis and respiration rates, induction of nonphotochemical quenching of chlorophyll fluorescence). The expression of the genes which encode the enzymes participating in the detoxification of reactive oxygen species (APX1, CAT1, FSD1, MSD1) was measured. The other gene measured was one required for plastoquinone and α-tocopherol biosynthesis (VTE3). The application of heavy metal ions partly inhibited growth and biosynthesis of chlorophyll. The growth inhibition was accompanied by enhanced lipid peroxidation. An increase in the content of prenyllipid antioxidants was observed in cultures exposed to Cr2O7(2-), Cd(2+) (α- and γ-tocopherol and plastoquinone) and Cu(2+) (only tocopherols). The induction of nonphotochemical quenching was enhanced in cultures exposed to Cu(2+), Cr2O7(2-) and Cd(2+), as compared to the control. Chronic heavy metal-induced stress led to changes in gene expression dependent on the type and concentration of heavy metal ions. The up-regulation of antioxidant enzymes was usually accompanied by the up-regulation of the VTE3 gene."

abs5 = "Isoprenoid quinones and chromanols in plants fulfill both signaling and antioxidant functions under oxidative stress. The redox state of the plastoquinol pool (PQ-pool), which is modulated by interaction with reactive oxygen species (ROS) during oxidative stress, has a major regulatory function in both short- and long-term acclimatory responses. By contrast, the scavenging of ROS by prenyllipids affects signaling pathways where ROS play a role as signaling molecules. As the primary antioxidants, isoprenoid quinones and chromanols are synthesized under high-light stress in response to any increased production of ROS. During photo-oxidative stress, these prenyllipids are continuously synthesized and oxidized to other compounds. In turn, their oxidation products (hydroxy-plastochromanol, plastoquinol-C, plastoquinone-B) can still have an antioxidant function. The oxidation products of isoprenoid quinones and chromanols formed specifically in the face of singlet oxygen, can be indicators of singlet oxygen stress."

abs6 = "In the present study, we have identified new prenyllipid metabolites formed during high light stress in Arabidopsis thaliana, whose origin and function remained unknown so far. It was found that plastoquinone-C accumulates mainly in the reduced form under high light conditions, as well as during short-term excess light illumination both in the wild-type and tocopherol biosynthetic vte1 mutant, suggesting that plastoquinone-C, a singlet oxygen-derived prenyllipid, is reduced in chloroplasts by photosystem II or enzymatically, outside thylakoids. Plastoquinone-B, a fatty acid ester of plastoquinone-C, was identified for the first time in Arabidopsis in high light grown wild-type plants and during short-time, excess light illumination of the wild-type plants and the vte1 mutant. The gene expression analysis showed that vte2 gene is most pronouncedly up-regulated among the prenyllipid biosynthetic genes under high light and induction of its expression is mainly caused by an increased level of singlet oxygen, as was demonstrated in experiments with D2 O-treated plants under excess light conditions."

abs7 = "During their lifetime, plants need to adapt to a changing environment, including light and temperature. To understand how these factors influence plant growth, we investigated the physiological and antioxidant responses of two Arabidopsis accessions, Shahdara (Sha) from the Shahdara valley (Tajikistan, Central Asia) in a mountainous area and Lovvik-5 (Lov-5) from northern Sweden to different light and temperature conditions. These accessions originate from different latitudes and have different life strategies, both of which are known to be influenced by light and temperature. We showed that both accessions grew better in high-light and at a lower temperature (16°C) than in low light and at 23°C. Interestingly, Sha had a lower chlorophyll content but more efficient non-photochemical quenching than Lov-5. Sha, also showed a higher expression of vitamin E biosynthetic genes. We did not observe any difference in the antioxidant prenyllipid level under these conditions. Our results suggest that the mechanisms that keep the plastoquinone (PQ)-pool in more oxidized state could play a role in the adaptation of these accessions to their local climatic conditions."

abs8 = "In the present study, we have shown that hydroxy-plastochromanol and plastoquinone-C, the hydroxy derivatives of plastochromanol and plastoquinone-9, respectively, are specifically formed from the parent compounds upon action of singlet oxygen and can be regarded as stable, specific, natural products of singlet oxygen action during photo-oxidative stress in vivo. The presented data indicate that plastoquinone-C formation dominates mainly during relatively short periods of high light stress where efficient production of singlet oxygen takes place, whereas hydroxy-plastochromanol is rather formed under conditions of long-term, less pronounced generation of singlet oxygen. An interesting observation was that hydroxy-plastochromanol is formed even at very low light conditions (5-10 μmol photons m(-2) s(-1)), indicating that singlet oxygen is generated not only during high light stress but also its formation by photosystem II is inseparably connected with the functioning of this photosystem even at the lowest light intensities."

abs9 = "Lipid peroxidation is an oxidation reaction leading to the generation of lipid hydroperoxides. Here we present comparative data on the inhibition of lipid peroxidation by a variety of biological prenyllipids in liposomes prepared from natural lipid membranes. Lipid peroxidation was initiated by hydrophilic and hydrophobic azo initiators, as well as by singlet oxygen generated via photosensitized reaction of hydrophobic zinc tetraphenylporphine. When lipid peroxidation was initiated in the water phase, tocopherols and plastochromanol-8 were more effective than prenylquinols, such as plastoquinol-9, ubiquinol-10 or α-tocopherolquinol. However, if the peroxidation was initiated within the hydrophobic interior of liposome membranes, long-chain prenyllipids, such as plastoquinol-9 and plastochromanol-8, were considerably more active than tocopherols in the inhibition of the reaction. In the latter system, tocopherols showed even prooxidant activity. The prooxidant activity of α-tocopherol was prevented by plastoquinol, suggesting the reduction of α-tocopheroxyl radical by the quinol. All the investigated prenyllipids were able to inhibit singlet oxygen-mediated lipid peroxidation but the most active were prenylquinols in this respect. Among all the prenyllipids investigated, plastochromanol-8 was the most versatile antioxidant in the inhibition of lipid peroxidation initiated by the three different methods."

abs10 = "In the present study, we have performed comparative analysis of different prenyllipids in Chlamydomonas reinhardtii cultures during high light stress under variety of conditions (presence of inhibitors, an uncoupler, heavy water). The obtained results indicate that plastoquinol is more active than α-tocopherol in scavenging of singlet oxygen generated in photosystem II. Besides plastoquinol, also its oxidized form, plastoquinone shows antioxidant action during the stress conditions, resulting in formation of plastoquinone-C, whose level can be regarded as an indicator of singlet oxygen oxidative stress in vivo. The pronounced stimulation of α-tocopherol consumption and α-tocopherolquinone formation by an uncoupler, FCCP, together with the results of additional model system studies, led to the suggestion that α-tocopherol can be recycled in thylakoid membranes under high light conditions from 8a-hydroperoxy-α-tocopherone, the primary oxidation product of α-tocopherol by singlet oxygen."

abs11 = "Isoprenoid quinones are one of the most important groups of compounds occurring in membranes of living organisms. These compounds are composed of a hydrophilic head group and an apolar isoprenoid side chain, giving the molecules a lipid-soluble character. Isoprenoid quinones function mainly as electron and proton carriers in photosynthetic and respiratory electron transport chains and these compounds show also additional functions, such as antioxidant function. Most of naturally occurring isoprenoid quinones belong to naphthoquinones or evolutionary younger benzoquinones. Among benzoquinones, the most widespread and important are ubiquinones and plastoquinones. Menaquinones, belonging to naphthoquinones, function in respiratory and photosynthetic electron transport chains of bacteria. Phylloquinone K(1), a phytyl naphthoquinone, functions in the photosynthetic electron transport in photosystem I. Ubiquinones participate in respiratory chains of eukaryotic mitochondria and some bacteria. Plastoquinones are components of photosynthetic electron transport chains of cyanobacteria and plant chloroplasts. Biosynthetic pathway of isoprenoid quinones has been described, as well as their additional, recently recognized, diverse functions in bacterial, plant and animal metabolism."

abs12 = "Prenylquinones are a group of compounds occurring in all living cells. In their structure a polar head group undergoing redox reactions and a long, hydrophobic side-chain can be found. Due to their amphiphilic character, these compounds are mainly located in biological membranes where they function as electron and proton carriers in the photosynthetic and respiratory electron transport chains. Prenylquinones play also additional roles such as antioxidants, and other more specific functions such as enzyme cofactors. Based on the ring structure, different groups of prenylquinones are distinguished: menaquinones, phylloquinone, ubiquinones and plastoquinones, although also other representatives of this group are known, e.g. tocopherolquinones. Frequently, biosynthesis ability of a given kind of prenylquinones is limited to a certain group of organisms. This review describes the structure, function and biosynthesis of most common prenylquinones."

abs13 = "Zeaxanthin epoxidase (ZE, E.C. 1.14.13.90), an enzyme belonging to the lipocalin superfamily, catalyses the conversion of zeaxanthin to antheraxanthin and violaxanthin. These reactions are part of the xanthophyll biosynthetic pathway and the xanthophyll cycle. The role of carotenoids in the dissipation of excessive light energy has been widely studied using mutants with a disabled carotenoid biosynthetic pathway. In this paper, the transgenic line MaZEP7 with partially disabled ZE activity is described and compared with wild-type plants and npq2 mutant lacking active ZE. We examined the presence and the abundance of aba1 transcripts, measured pigment composition, xanthophyll cycle functioning and chlorophyll fluorescence in all three lines. The MaZEP7 line contains additional copies of the aba1 gene introduced by agroinfiltration, but no enhanced aba1 transcript level was observed. In addition, ZE activity in MaZEP7 was impaired, resulting in an altered xanthophyll profile. In dark-adapted plants, violaxanthin and neoxanthin levels were lower than in wild-type plants, whereas antheraxanthin and zeaxanthin levels were considerably higher. The presence of lutein epoxide was also observed. Violaxanthin levels changed only minimally during light exposition, whereas antheraxanthin was converted to zeaxanthin and there was no epoxidation during the course of the experiment indicating disturbed xanthophyll cycle functioning. The amounts of carotenoids and chlorophylls on a dry weight basis and chl a/chl b ratio were similar in all lines. The presence of epoxidated pigments in MaZEP7 plants indicates that epoxidation occurs, but it is likely very slow. Chlorophyll fluorescence measurements showed that the dependence of electron transport rates on light intensity for the MaZEP7 line resembled the npq2 mutant. Kinetic measurements showed that the MaZEP7 line exhibited very rapid induction and a high steady-state value of non-photochemical quenching."

doc_complete = [abs1, abs2, abs3, abs4, abs5, abs6, abs7, abs8, abs9, abs10, abs11, abs12, abs13]

stop = set(stopwords.words('english'))
exclude = set(string.punctuation)
lemma = WordNetLemmatizer()
def clean(doc):
    stop_free = " ".join([i for i in doc.lower().split() if i not in stop])
    punc_free = ''.join(ch for ch in stop_free if ch not in exclude)
    normalized = " ".join(lemma.lemmatize(word) for word in punc_free.split())
    return normalized

doc_clean = [clean(doc).split() for doc in doc_complete]


# Creating the term dictionary of our courpus, where every unique term is
# assigned an index. 
dictionary = corpora.Dictionary(doc_clean)

# Converting list of documents (corpus) into Document Term Matrix using
# dictionary prepared above.
doc_term_matrix = [dictionary.doc2bow(doc) for doc in doc_clean]

# Creating the object for LDA model using gensim library
Lda = gensim.models.ldamodel.LdaModel

# Running and Trainign LDA model on the document term matrix.
ldamodel = Lda(doc_term_matrix, num_topics=3, id2word = dictionary, passes=50)

print(ldamodel.print_topics(num_topics=3, num_words=3))
