# http://www.ncbi.nlm.nih.gov/pubmed/?term=%C5%81ABUZ+JUSTYNA

from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
import string
import gensim
from gensim import corpora

abs1 = "Phototropins are plant photoreceptors which regulate numerous responses to blue light, including chloroplast relocation. Weak blue light induces chloroplast accumulation, whereas strong light leads to an avoidance response. Two Arabidopsis phototropins are characterized by different light sensitivities. Under continuous light, both can elicit chloroplast accumulation, but the avoidance response is controlled solely by phot2. As well as continuous light, brief light pulses also induce chloroplast displacements. Pulses of 0.1s and 0.2s of fluence rate saturating the avoidance response lead to transient chloroplast accumulation. Longer pulses (up to 20s) trigger a biphasic response, namely transient avoidance followed by transient accumulation. This work presents a detailed study of transient chloroplast responses in Arabidopsis. Phototropin mutants display altered chloroplast movements as compared with the wild type: phot1 is characterized by weaker responses, while phot2 exhibits enhanced chloroplast accumulation, especially after 0.1s and 0.2s pulses. To determine the cause of these differences, the abundance and phosphorylation levels of both phototropins, as well as the interactions between phototropin molecules are examined. The formation of phototropin homo- and heterocomplexes is the most plausible explanation of the observed phenomena. The physiological consequences of this interplay are discussed, suggesting the universal character of this mechanism that fine-tunes plant reactions to blue light. Additionally, responses in mutants of different protein phosphatase 2A subunits are examined to assess the role of protein phosphorylation in signaling of chloroplast movements."

abs2 = "Calcium is involved in the signal transduction pathway from phototropins, the blue light photoreceptor kinases which mediate chloroplast movements. The chloroplast accumulation response in low light is controlled by both phot1 and phot2, while only phot2 is involved in avoidance movement induced by strong light. Phototropins elevate cytosolic Ca(2+) after activation by blue light. In higher plants, both types of chloroplast responses depend on Ca(2+), and internal calcium stores seem to be crucial for these processes. Yet, the calcium signatures generated after the perception of blue light by phototropins are not well understood. To characterize the localization of calcium in Arabidopsis mesophyll cells, loosely bound (exchangeable) Ca(2+) was precipitated with potassium pyroantimonate and analyzed by transmission electron microscopy followed by energy-dispersive X-ray microanalysis. In dark-adapted wild-type Arabidopsis leaves, calcium precipitates were observed at the cell wall, where they formed spherical structures. After strong blue light irradiation, calcium at the apoplast prevailed, and bigger, multilayer precipitates were found. Spherical calcium precipitates were also detected at the tonoplast. After red light treatment as a control, the precipitates at the cell wall were smaller and less numerous. In the phot2 and phot1phot2 mutants, calcium patterns were different from those of wild-type plants. In both mutants, no elevation of calcium after blue light treatment was observed at the cell periphery (including the cell wall and a fragment of cytoplasm). This result confirms the involvement of phototropin2 in the regulation of Ca(2+) homeostasis in mesophyll cells."

abs3 = "Chloroplast movements in Arabidopsis thaliana are controlled by two blue light photoreceptors, phototropin1 and phototropin2. Under weak blue light chloroplasts gather at cell walls perpendicular to the direction of incident light. This response, called chloroplast accumulation, is redundantly regulated by both phototropins. Under strong blue light chloroplasts move to cell walls parallel to the direction of incident light, this avoidance response being solely dependent on phototropin2. Temperature is an important factor in modulating chloroplast relocations. Here we focus on temperature effects in Arabidopsis leaves. At room temperature, under medium blue light chloroplasts start to move to cell walls parallel to the light direction and undergo a partial avoidance response. In the same conditions, at low temperatures the avoidance response is strongly enhanced-chloroplasts behave as if they were responding to strong light. Higher sensitivity of avoidance response is correlated with changes in gene expression. After cold treatment, in darkness, the expression of phototropin1 is down-regulated, while phototropin2 levels are up-regulated. The motile system of chloroplasts in Arabidopsis is more sensitive to blue light at low temperatures, similar to other species studied before. The physiological role of the cold-enhancement of the avoidance response is explained in the context of phototropin levels, photochemical activities and signaling in the cell."

abs4 = "Phototropins are plasma membrane-localized UVA/blue light photoreceptors which mediate phototropism, inhibition of primary hypocotyl elongation, leaf positioning, chloroplast movements, and stomatal opening. Blue light irradiation activates the C-terminal serine/threonine kinase domain of phototropin which autophosphorylates the receptor. Arabidopsis thaliana encodes two phototropins, phot1 and phot2. In response to blue light, phot1 moves from the plasma membrane into the cytosol and phot2 translocates to the Golgi complex. In this study the molecular mechanism and route of blue-light-induced phot2 trafficking are demonstrated. It is shown that Atphot2 behaves in a similar manner when expressed transiently under 35S or its native promoter. The phot2 kinase domain but not blue-light-mediated autophosphorylation is required for the receptor translocation. Using co-localization and western blotting, the receptor was shown to move from the cytoplasm to the Golgi complex, and then to the post-Golgi structures. The results were confirmed by brefeldin A (an inhibitor of the secretory pathway) which disrupted phot2 trafficking. An association was observed between phot2 and the light chain2 of clathrin via bimolecular fluorescence complementation. The fluorescence was observed at the plasma membrane. The results were confirmed using co-immunoprecipitation. However, tyrphostin23 (an inhibitor of clathrin-mediated endocytosis) and wortmannin (a suppressor of receptor endocytosis) were not able to block phot2 trafficking, indicating no involvement of receptor endocytosis in the formation of phot2 punctuate structures. Protein turnover studies indicated that the receptor was continuously degraded in both darkness and blue light. The degradation of phot2 proceeded via a transport route different from translocation to the Golgi complex."

abs5 = "In angiosperms, light-dependent chloroplast movements are exclusively mediated by UVA/blue light receptors - phototropins. The two photoreceptors of Arabidopsis thaliana, phot1 and phot2, have overlapping roles in the control of these movements. Experiments performed in different plant species point to the participation of phosphoinositides in blue light-controlled chloroplast relocations. Here, we report a summary of recent findings presenting the involvement of phosphatidylinositol 4,5-bisphosphate as well as phosphatidylinositol 3- and 4-phosphates in weak blue light-mediated (accumulation) and strong blue light-mediated (avoidance) responses of chloroplasts. The blue light-activated alterations in phosphoinositide concentration are partly responsible for cytosolic Ca (2+) changes. Ca (2+) influx from apoplast does not seem to be involved in the mechanism of movement responses. In summary, interplay between phosphoinositides and intracellular Ca (2+) regulates chloroplast redistribution in response to blue light in higher plants."

abs6 = "Phototropins are UVA/blue-light receptors involved in controlling the light-dependent physiological responses which serve to optimize the photosynthetic activity of plants and promote growth. The phototropin-induced phosphoinositide (PI) metabolism has been shown to be essential for stomatal opening and phototropism. However, the role of PIs in phototropin-induced chloroplast movements remains poorly understood. The aim of this work is to determine which PI species are involved in the control of chloroplast movements in Arabidopsis and the nature of their involvement. We present the effects of the inactivation of phospholipase C (PLC), PI3-kinase (PI3K) and PI4-kinase (PI4K) on chloroplast relocations in Arabidopsis. The inhibition of the phosphatidylinositol 4,5-bisphospahte [PI(4,5)P2]-PLC pathway, using neomycin and U73122, suppressed the phot2-mediated chloroplast accumulation and avoidance responses, without affecting movement responses controlled by phot1. On the other hand, PI3K and PI4K activities are more restricted to phot1- and phot2-induced weak-light responses. The inactivation of PI3K and PI4K by wortmannin and LY294002 severely affected the weak blue-light-activated accumulation response but had little effect on the strong blue-light-activated avoidance response. The inhibitory effect observed with PI metabolism inhibitors is, at least partly, due to a disturbance in Ca(2+) ((c)) signaling. Using the transgenic aequorin system, we show that the application of these inhibitors suppresses the blue-light-induced transient Ca(2+) ((c)) rise. These results demonstrate the importance of PIs in chloroplast movements, with the PI(4,5)P2-PLC pathway involved in phot2 signaling while PI3K and PI4K are required for the phot1- and phot2-induced accumulation response. Our results suggest that these PIs modulate cytosolic Ca(2+) signaling during movements."

abs7 = "Phototropins are blue light receptors, which play different roles during plant development. Two phototropins of Arabidopsis thaliana, phot1 and phot2, have strongly overlapping functions. In seedlings, both photoreceptors are responsible for phototropism. In mature leaves they redundantly regulate leaf shape, stomatal opening, and the accumulation of chloroplasts, whereas phototropin2 alone controls chloroplast avoidance response. Light not only activates phototropins, but also affects the level of their expression. In Arabidopsis seedlings, PHOT1 is downregulated and PHOT2 is upregulated by light. Since data on transcription levels of phototropins in mature Arabidopsis leaves is scarce, a comprehensive real-time PCR study of PHOT1 and PHOT2 expression during development was performed, from seedlings to senescing leaves. So far, neither the phototropin expression nor its modulation by light have been investigated during senescence. The results show that the general regulation pattern remains conserved during Arabidopsis lifecycle, whereas the level of transcripts fluctuates over time, pointing to the significance of the light control for functioning of phototropins. The second part of the study determined the influence of photosynthesis-derived signals and photoreceptor-activated transduction pathways on phototropin mRNA levels. The effects of blue and red light were examined using Arabidopsis mutant lines deficient in photoreceptors. The results reveal a complex network of interactions between these receptors in the regulation of phototropin transcription profiles. Cryptochrome1 and phytochromeB appear to be main photoreceptors involved in the regulation of PHOT1 transcript accumulation. The expression of PHOT2 is dependent on both cryptochromes and phytochromeA."

abs8 = "Chloroplast movements are among the mechanisms allowing plants to cope with changes in their environment. Chloroplasts accumulate at illuminated cell areas under weak light while they avoid areas exposed to strong light. These directional responses may be controlled by blue and/or red light, depending on the plant group. In terrestrial angiosperms only the blue light perceived by phototropins is active. The last decade has seen a rapid development of studies on the mechanism of directional chloroplast movements, which started with an identification of the photoreceptors. A forward genetic approach has been used to identify the components which control chloroplast movements. This review summarizes the current state of research into the signalling pathways which lead to chloroplast responses. First, the molecular properties of phototropins are presented, followed by a characterization both of proteins which are active downstream of phototropins and of secondary messengers. Finally, cross-talk between light signalling involved in chloroplast movements and other signalling pathways is discussed."

abs9 = "We found that the levels of mRNA of two enzymes involved in chlorophyll catabolism in Arabidopsis (Arabidopsis thaliana), products of two chlorophyllase genes, AtCLH1 and AtCLH2, dramatically increase (by almost 100- and 10-fold, respectively) upon illumination with white light. The measurements of photosystem II quantum efficiency in 3-(3,4-dichlorophenyl)-1,1-dimethylurea-inhibited leaves show that their expression is not related to photosynthesis but mediated by photoreceptors. To identify the photoreceptors involved, we used various light treatments and Arabidopsis photoreceptor mutants (cry1, cry2, cry1cry2, phot1, phot2, phot1phot2, phyA phyB, phyAphyB). In wild-type Columbia, the amount of transcripts of both genes increase after white-light irradiation but their expression profile and the extent of regulation differ considerably. Blue and red light is active in the case of AtCLH1, whereas only blue light raises the AtCLH2 mRNA level. The fundamental difference is the extent of up-regulation, higher by one order of magnitude in AtCLH1. Both blue and red light is active in the induction of AtCLH1 expression in all mutants, pointing to a complex control network and redundancy between photoreceptors. The blue-specific up-regulation of the AtCLH2 transcript is mediated by cryptochromes and modulated by phototropin1 and phytochromes. Individually darkened leaves were used to test the effects of senescence on the expression of AtCLH1 and AtCLH2. The expression profile of AtCLH1 remains similar to that found in nonsenescing leaves up to 5 d after darkening. In contrast, the light induction of AtCLH2 mRNA declines during dark treatment. These results demonstrate that the expression of enzymes involved in chlorophyll catabolism is light controlled."

doc_complete = [abs1, abs2, abs3, abs4, abs5, abs6, abs7, abs8, abs9]

stop = set(stopwords.words('english'))
exclude = set(string.punctuation)
lemma = WordNetLemmatizer()
def clean(doc):
    stop_free = " ".join([i for i in doc.lower().split() if i not in stop])
    punc_free = ''.join(ch for ch in stop_free if ch not in exclude)
    normalized = " ".join(lemma.lemmatize(word) for word in punc_free.split())
    return normalized

doc_clean = [clean(doc).split() for doc in doc_complete]


# Creating the term dictionary of our courpus, where every unique term is
# assigned an index. 
dictionary = corpora.Dictionary(doc_clean)

# Converting list of documents (corpus) into Document Term Matrix using
# dictionary prepared above.
doc_term_matrix = [dictionary.doc2bow(doc) for doc in doc_clean]

# Creating the object for LDA model using gensim library
Lda = gensim.models.ldamodel.LdaModel

# Running and Trainign LDA model on the document term matrix.
ldamodel = Lda(doc_term_matrix, num_topics=3, id2word = dictionary, passes=50)

print(ldamodel.print_topics(num_topics=3, num_words=3))

