---
output: html_document
---

# Feature selection
#### Debarati Dutta

[How to perform feature selection (i.e. pick important variables) using Boruta Package in R ?](https://www.analyticsvidhya.com/blog/2016/03/select-important-variables-boruta-package/)

[Author: Debarati Dutta](https://ca.linkedin.com/in/debaratidutta8)

1. Data preparation

```{r}
setwd("/home/bartosz/Downloads/loan3/")
traindata = read.csv("train.csv", header = T, stringsAsFactors = F)
str(traindata)
names(traindata) = gsub("_", "", names(traindata))
summary(traindata)
traindata[traindata == ""] = NA
traindata = traindata[complete.cases(traindata),]
convert = c(2:6, 11:13)
traindata[,convert] = data.frame(apply(traindata[convert], 2, as.factor))
```

2. Into the forest (with Boruta)

```{r}
set.seed(123)
library(Boruta)
boruta.train = Boruta(LoanStatus ~ .-LoanID, data = traindata, doTrace = 2)
print(boruta.train)

plot(boruta.train, xlab = "", xaxt = "n")
lz<-lapply(1:ncol(boruta.train$ImpHistory),function(i)
  boruta.train$ImpHistory[is.finite(boruta.train$ImpHistory[,i]),i])
names(lz) <- colnames(boruta.train$ImpHistory)
Labels <- sort(sapply(lz,median))
axis(side = 1,las=2,labels = names(Labels),
     at = 1:ncol(boruta.train$ImpHistory), cex.axis = 0.7)

final.boruta <- TentativeRoughFix(boruta.train)
print(final.boruta)

getSelectedAttributes(final.boruta, withTentative = F)
boruta.df <- attStats(final.boruta)
class(boruta.df)
print(boruta.df)
```

3. Comparison with other packages

```{r}
library(caret)
library(randomForest)
set.seed(123)
control <- rfeControl(functions=rfFuncs, method="cv", number=10)
rfe.train <- rfe(traindata[,2:12], traindata[,13], sizes=1:12, rfeControl=control)
rfe.train
plot(rfe.train, type=c("g", "o"), cex = 1.0, col = 1:11)
predictors(rfe.train)
```